[test]
pathIgnorePatterns = ["out/**"]
coveragePathIgnorePatterns = ["src/testSelf*.test.ts"]
onlyFailures = true
timeout = 5000

[install]
minimumReleaseAge = 604800 # 7 days
minimumReleaseAgeExcludes = [
	"typescript",

	"oxlint",
	"@oxlint/binding-darwin-x64",
	"@oxlint/binding-freebsd-x64",
	"@oxlint/binding-darwin-arm64",
	"@oxlint/binding-android-arm64",
	"@oxlint/binding-linux-x64-gnu",
	"@oxlint/binding-linux-x64-musl",
	"@oxlint/binding-win32-x64-msvc",
	"@oxlint/binding-linux-arm64-gnu",
	"@oxlint/binding-linux-ppc64-gnu",
	"@oxlint/binding-linux-s390x-gnu",
	"@oxlint/binding-win32-ia32-msvc",
	"@oxlint/binding-android-arm-eabi",
	"@oxlint/binding-linux-arm64-musl",
	"@oxlint/binding-win32-arm64-msvc",
	"@oxlint/binding-linux-riscv64-gnu",
	"@oxlint/binding-openharmony-arm64",
	"@oxlint/binding-linux-riscv64-musl",
	"@oxlint/binding-linux-arm-gnueabihf",
	"@oxlint/binding-linux-arm-musleabihf",

	"oxfmt",
	"@oxfmt/binding-darwin-x64",
	"@oxfmt/binding-freebsd-x64",
	"@oxfmt/binding-darwin-arm64",
	"@oxfmt/binding-android-arm64",
	"@oxfmt/binding-linux-x64-gnu",
	"@oxfmt/binding-linux-x64-musl",
	"@oxfmt/binding-win32-x64-msvc",
	"@oxfmt/binding-linux-arm64-gnu",
	"@oxfmt/binding-linux-ppc64-gnu",
	"@oxfmt/binding-linux-s390x-gnu",
	"@oxfmt/binding-win32-ia32-msvc",
	"@oxfmt/binding-android-arm-eabi",
	"@oxfmt/binding-linux-arm64-musl",
	"@oxfmt/binding-win32-arm64-msvc",
	"@oxfmt/binding-linux-riscv64-gnu",
	"@oxfmt/binding-openharmony-arm64",
	"@oxfmt/binding-linux-riscv64-musl",
	"@oxfmt/binding-linux-arm-gnueabihf",
	"@oxfmt/binding-linux-arm-musleabihf",
]
linker = "isolated"
globalStore = true
