import { $ } from "bun"
import { execSync } from "node:child_process"
import fs from "node:fs"
import os from "node:os"
import path from "node:path"
import { parseArgs, styleText as c } from "node:util"

const { values } = parseArgs({
	args: Bun.argv.slice(2),
	options: {
		diff: { type: "string" },
		help: { short: "h", type: "boolean" },
		now: { type: "boolean" },
		out: { type: "string" },
	},
})

if (values.help) {
	console.log(`${c("bold", "Usage:")} ${c("yellow", "bun scripts/size.js [options]")}

${c("bold", "Options:")}
  -h, --help     ${c("dim", "Show this help")}
  --diff <ref>   ${c("dim", "Compare current branch size with <ref>")}
  --out <file>   ${c("dim", "Write results to <file>")}
  --now          ${c("dim", "Use synthetic data for table testing")}
`)
	process.exit(0)
}

function parseSizeToBytes(sizeStr) {
	const match = sizeStr.trim().match(/^([\d.]+)\s*([a-zA-Z]+)$/)
	if (!match) return 0
	const val = parseFloat(match[1])
	const unit = match[2].toUpperCase()
	switch (unit) {
		case "B":
			return val
		case "KB":
			return val * 1024
		case "MB":
			return val * 1024 * 1024
		case "GB":
			return val * 1024 * 1024 * 1024
		default:
			return val
	}
}

function formatBytes(bytes) {
	if (Math.abs(bytes) === 0) return "0 B"
	const k = 1024
	const sizes = ["B", "KB", "MB", "GB"]
	const i = Math.floor(Math.log(Math.abs(bytes)) / Math.log(k))
	const val = bytes / Math.pow(k, i)
	return `${i === 0 ? Math.round(val) : val.toFixed(2)} ${sizes[i]}`
}

function formatSizeDiff(diff) {
	if (diff === 0) return "0 B"
	const arrow = diff > 0 ? "↑ +" : "↓ -"
	return `${arrow}${formatBytes(Math.abs(diff))}`
}

function padRight(str, len) {
	return str + " ".repeat(Math.max(0, len - str.length))
}

function getDirSize(dir, visited = new Set()) {
	try {
		const realPath = fs.realpathSync(dir)
		if (visited.has(realPath)) return 0
		visited.add(realPath)
	} catch {
		return 0
	}

	let totalSize = 0
	let files = []
	try {
		files = fs.readdirSync(dir)
	} catch {
		return 0
	}

	for (const file of files) {
		try {
			const resPath = path.join(dir, file)
			const stats = fs.statSync(resPath)
			if (stats.isDirectory()) {
				totalSize += getDirSize(resPath, visited)
			} else if (stats.isFile()) {
				totalSize += stats.size
			}
		} catch {}
	}
	return totalSize
}

function getSubDependencies(depDir) {
	try {
		const depPkgJsonPath = path.join(depDir, "package.json")
		if (!fs.existsSync(depPkgJsonPath)) return []
		const depPkg = JSON.parse(fs.readFileSync(depPkgJsonPath, "utf8"))
		return Object.keys(depPkg.dependencies || {})
	} catch {
		return []
	}
}

function getProductionDependenciesSizes(dir) {
	const resolvedDeps = new Set()
	const queue = []

	try {
		const pkgJsonPath = path.join(dir, "package.json")
		if (fs.existsSync(pkgJsonPath)) {
			const pkg = JSON.parse(fs.readFileSync(pkgJsonPath, "utf8"))
			// Only grab production dependencies (ignoring devDependencies)
			const deps = pkg.dependencies || {}
			for (const dep of Object.keys(deps)) {
				queue.push(dep)
			}
		}
	} catch {}

	let totalSize = 0
	const visited = new Set()

	while (queue.length > 0) {
		const dep = queue.shift()
		if (resolvedDeps.has(dep)) continue
		resolvedDeps.add(dep)

		const depDir = path.join(dir, "node_modules", dep)
		if (!fs.existsSync(depDir)) continue

		totalSize += getDirSize(depDir, visited)

		// Recursively add transitive production dependencies
		const subDeps = getSubDependencies(depDir)
		for (const subDep of subDeps) {
			queue.push(subDep)
		}
	}

	return totalSize
}

function getPackageSize(dir) {
	try {
		const stdout = execSync("bun pm pack", {
			cwd: dir,
			encoding: "utf8",
			stdio: ["ignore", "pipe", "ignore"],
		})

		// Clean up tarball generated by bun pm pack
		const files = fs.readdirSync(dir)
		for (const file of files) {
			if (file.endsWith(".tgz")) {
				fs.unlinkSync(path.join(dir, file))
			}
		}

		const packedSizeMatch = stdout.match(/Packed size:\s*([\d.]+\s*[a-zA-Z]+)/i)

		const ownBytes = packedSizeMatch ? parseSizeToBytes(packedSizeMatch[1]) : 0
		const ownSizeStr = formatBytes(ownBytes)

		const depsBytes = getProductionDependenciesSizes(dir)
		const totalBytes = ownBytes + depsBytes

		return {
			ownBytes,
			ownSizeStr,
			totalBytes,
			totalSizeStr: formatBytes(totalBytes),
		}
	} catch (e) {
		process.stderr.write(`Failed to calculate package size in ${dir}: ${e}\n`)
		return null
	}
}

function getPackageSizeTable(current, base) {
	const headers = base ? ["Item", "Size", "Change"] : ["Item", "Size"]

	const rows = base
		? [
				[
					"Own Size",
					`${base.ownSizeStr} → ${current.ownSizeStr}`,
					formatSizeDiff(current.ownBytes - base.ownBytes),
				],
				[
					"Total Size",
					`${base.totalSizeStr} → ${current.totalSizeStr}`,
					formatSizeDiff(current.totalBytes - base.totalBytes),
				],
			]
		: [
				["Own Size", current.ownSizeStr],
				["Total Size", current.totalSizeStr],
			]

	const colWidths = headers.map((h, idx) => {
		let maxLen = h.length
		for (const row of rows) {
			maxLen = Math.max(maxLen, row[idx].length)
		}
		return maxLen
	})

	const headerLine = headers
		.map((h, idx) => padRight(h, colWidths[idx]))
		.join("  ")
		.trimEnd()
	const separatorLine = colWidths.map((w) => "-".repeat(w)).join("  ")
	const rowLines = rows.map((row) => {
		return row
			.map((val, idx) => padRight(val, colWidths[idx]))
			.join("  ")
			.trimEnd()
	})

	return [headerLine, separatorLine, ...rowLines].join("\n") + "\n"
}

async function main() {
	let currentSize = null
	let baseSize = null

	if (values.now) {
		currentSize = {
			ownBytes: 170000,
			ownSizeStr: "166.02 KB",
			totalBytes: 260000,
			totalSizeStr: "253.91 KB",
		}
		baseSize = {
			ownBytes: 162998,
			ownSizeStr: "159.18 KB",
			totalBytes: 250000,
			totalSizeStr: "244.14 KB",
		}
	} else {
		if (values.diff) {
			try {
				process.stderr.write(`Building current branch...\n`)
				const build = await $`bun install && bun run prod`.nothrow().quiet()
				if (build.exitCode !== 0) {
					process.stderr.write(`Failed to build current branch\n`)
					process.exit(1)
				}
			} catch (e) {
				process.stderr.write(`Failed to build current branch: ${e}\n`)
				process.exit(1)
			}
		}

		currentSize = getPackageSize(process.cwd())

		if (values.diff) {
			const tmpDir = path.join(os.tmpdir(), `bench-size-${Date.now()}`)
			try {
				process.stderr.write(`Creating temporary worktree at ${tmpDir} for ${values.diff}...\n`)
				const worktreeAdd = await $`git worktree add --detach "${tmpDir}" ${values.diff}`
					.nothrow()
					.quiet()

				if (worktreeAdd.exitCode !== 0) {
					throw new Error(`Failed to create worktree for ${values.diff}`)
				}

				process.stderr.write(`Building ${values.diff} in worktree...\n`)
				const worktreeBuild = await $`cd "${tmpDir}" && bun install && bun run prod`
					.nothrow()
					.quiet()

				if (worktreeBuild.exitCode !== 0) {
					throw new Error(`Failed to build worktree for ${values.diff}`)
				}

				baseSize = getPackageSize(tmpDir)
			} catch (e) {
				process.stderr.write(`${e.message || e}\n`)
				process.exitCode = 1
			} finally {
				process.stderr.write(`Cleaning up temporary worktree at ${tmpDir}...\n`)
				await $`git worktree remove --force "${tmpDir}"`.nothrow().quiet()
			}
		}
	}

	if (!currentSize) {
		process.exit(1)
	}

	const sizeTable = getPackageSizeTable(currentSize, baseSize)

	if (values.out) {
		fs.writeFileSync(values.out, sizeTable)
	}

	process.stdout.write(sizeTable)
}

main().catch((e) => {
	console.error(e)
	process.exit(1)
})
